name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
  # 手動トリガー用
  workflow_dispatch:
    inputs:
      build_static_site:
        description: '静的サイトをビルドしてFTPアップロード'
        required: false
        default: false
        type: boolean

jobs:
  deploy-admin:
    name: Deploy Admin to Deno Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "magnolia-admin"
          entrypoint: "main.ts"
          root: "."

  build-and-deploy-static:
    name: Build and Deploy Static Site
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_static_site == 'true'

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Static Site
        run: |
          cd static-site
          deno run --allow-net --allow-read --allow-write build.ts
        env:
          API_URL: ${{ secrets.ADMIN_API_URL }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./static-site/dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
          
          
