name: Deploy Static Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 手動実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
        
    - name: Install dependencies
      run: |
        cd admin
        deno cache --reload main.ts
        
    - name: Build static site
      run: |
        cd admin/static-site
        deno run --allow-net --allow-read --allow-write build.ts
      env:
        DENO_DIR: ${{ github.workspace }}/.deno_dir
        API_URL: ${{ secrets.API_URL || 'http://localhost:8000' }}
        
    - name: List generated files
      run: |
        echo "Generated files:"
        find admin/static-site/dist -type f | sort
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: static-site-build
        path: admin/static-site/dist/
        retention-days: 1
        
    - name: Deploy to server
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd admin
        chmod +x scripts/deploy.sh
        ./scripts/deploy.sh
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
        API_URL: ${{ secrets.API_URL || 'http://localhost:8000' }}
          
          
